### ISSUE TITLE
update well symbols

### ISSUE THREAD

**Issue by paulfi** [bcgov/bc-aquifer-dashboard#14]
update well clustering to show a custom symbol
was thinking of using a blue circle symbol, or is there a  color scheme that we could use
to differentiate types of wells ie, observation wells vs other wells?

**Comment by IanLaingBCGov** [comment]
I think differentiating observation wells (MINISTRY_OBSERVATION_WELL_STAT = 'Active') from all of the others (blue?) is a good idea.

**Comment by paulfi** [comment]
changed colors to:
licenced = green
unlicenced = orange
active observation = red
