### ISSUE TITLE
search tool activation

### ISSUE THREAD

**Issue by paulfi** [bcgov/bc-aquifer-dashboard#15]
when the user enters a region or district name in the search box, it should zoom to it and highlight it!
can use the same layer that is being used to highlight an aquifer, just need to update the shape source for it to be the selected administrative area.

**Comment by IanLaingBCGov** [comment]
Line 200 (as of now) in filterEvents function in dashboarding.js

**Comment by IanLaingBCGov** [comment]
Nice zooming and highlighting of the Regions Paul. One glitch: 'Kootenay-Boundary Region' is NOT working. 
**** Project ID not found ****

Fixed this by removing '-1' from returnLayerByAttribute function in _makeamap.js_
i.e., `for (i=0;i<arLayers.length;i++) {`

**Comment by paulfi** [comment]
i did the same, haven't done a commit yet !
