### ISSUE TITLE
No result when Aquifer Clicked (could be just me, Ian)

### ISSUE THREAD

**Issue by IanLaingBCGov** [bcgov/bc-aquifer-dashboard#16]
No chooser popup (with overlapping aquifers) or appropriate actions (with single non-overlapping aquifer). This functionality is coded in
_function mapIdentify(e,lyr,initAqTag){_ 
in makeamap.js

I don't think anything has changed in the code, but it looks like the x, y being pumped into 
_var ajax = $.ajax({_ 
is not lat/long (but pixels instead, maybe?):

![image](https://user-images.githubusercontent.com/19290726/37379984-ac85f042-26f3-11e8-832a-4247fb25c7e1.png)

**Comment by wburt** [comment]
Yes.  WMS get featureInfo uses the map xy.  I enabled the provincial aquifer rollup so perhaps the hug is there

**Comment by IanLaingBCGov** [comment]
I feel the issue appeared even before your provincial aquifer rollup; as a test I reverted that commit and still had the issue. Can you guys see if the issue is happening to you?

**Comment by GrahamMacGregorBCGov** [comment]
I still get chooser popup

**Comment by IanLaingBCGov** [comment]
Thanks Graham, Glad it's still working for you. I suspect there's something wonky going on w/ my version at home. One minute it was working, the next it was not, with no code changes (that I was aware of).

**Comment by IanLaingBCGov** [comment]
Working again for some reason
