### ISSUE TITLE
Add information box when individual well is selected

### ISSUE THREAD

**Issue by GrahamMacGregorBCGov** [bcgov/bc-aquifer-dashboard#18]

**Comment by IanLaingBCGov** [comment]
Possibly a smallish popup in map so we're not re-configuring too many things in dashboard.

**Comment by GrahamMacGregorBCGov** [comment]
I have bound the data to the popup also. Next time we meet we can make a decision on which way we want to display well information.

**Comment by GrahamMacGregorBCGov** [comment]
Finished. Just need to decide if we put data in popup on map or information window. Both are complete

**Comment by IanLaingBCGov** [comment]
https://apps.nrs.gov.bc.ca/gwells/well/84690

**Comment by IanLaingBCGov** [comment]
'Link to Groundwater Well Information' button disappears with second well clicked. Need to persist with each well click.

**Comment by GrahamMacGregorBCGov** [comment]
Fixed button to persist
