### ISSUE TITLE
Inconsistent total features from obsWells object

### ISSUE THREAD

**Issue by GrahamMacGregorBCGov** [bcgov/bc-aquifer-dashboard#28]
The total observation wells in a aquifer is not consistent. When one is selected with three then i jump to another aquifer with 0 the obsWell.totalFeatures is still returning 3. Need to investigate.

**Comment by GrahamMacGregorBCGov** [comment]
I moved the get_obsWells(); call to just before the gwWells.callback(); My thoughts are that the callback was getting sent back and stats calculated before the obwell data had been updated. Thoughts Ian?

**Comment by IanLaingBCGov** [comment]
Good catch Graham. gwWells.data was being overwritten in the callback (doStuffWithWells). Your solution (above) works to grab the obsWells information before the gwWells.data is overwritten. Can you please commit that change and push to GitHub when you have a second?
