### ISSUE TITLE
Groundwater wells Information Box

### ISSUE THREAD

**Issue by IanLaingBCGov** [bcgov/bc-aquifer-dashboard#5]
when aquifer selected:
- total # of gw wells w/in an aquifer
- average depth of gw wells in aquifer
- number of observation wells in aquifer (Ian to figure out query of gwWells)
- nmber of null gw wells in aquifer

- want to see the wells categorized by some fields like WELL_USE_NAME, WATER_STATUS, WATER_DEPTH, BEDROCK_DEPTH, DEPTH_WELL_DRILLED, YIELD_VALUE (reported well yield)

**Comment by GrahamMacGregorBCGov** [comment]
Committed well info box mostly complete can potentially add a little more info to the box. Will assess before closing this.

**Comment by GrahamMacGregorBCGov** [comment]
Have added appropriate stats
